apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-init
  namespace: wordpress
spec:
  template:
    spec:
      containers:
      - name: wp-cli
        image: wordpress:cli
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Wait for WordPress to be ready
          until wp core is-installed --path=/var/www/html --allow-root; do echo "Waiting for WordPress installation..."; sleep 5; done
          
          # Configure WordPress
          wp core install \
            --path=/var/www/html \
            --url=http://$(kubectl get svc wordpress -n wordpress -o jsonpath='{.status.loadBalancer.ingress[0].ip}') \
            --title='My WordPress Site' \
            --admin_user=admin \
            --admin_password=admin@123 \
            --admin_email=admin@example.com \
            --allow-root
          
          # Update permalink structure
          wp option update permalink_structure '/%postname%/' --allow-root
          
          # Install and activate essential plugins
          wp plugin install \
            wordpress-seo \
            wordfence \
            w3-total-cache \
            --activate --allow-root
          
          # Configure basic settings
          wp option update blogdescription 'My WordPress Description' --allow-root
          wp option update timezone_string 'America/New_York' --allow-root
          wp option update blog_public 1 --allow-root
          
          # Create sample pages
          wp post create --post_type=page \
            --post_title='Home' \
            --post_status=publish \
            --post_content='Welcome to our website!' \
            --allow-root
          
          wp post create --post_type=page \
            --post_title='About Us' \
            --post_status=publish \
            --post_content='Learn more about us.' \
            --allow-root
          
          # Set homepage
          wp option update show_on_front 'page' --allow-root
          wp option update page_on_front $(wp post list --post_type=page --post_status=publish --posts_per_page=1 --pagename=home --format=ids --allow-root) --allow-root
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-pvc
      restartPolicy: Never
  backoffLimit: 4