apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  # These are base64 encoded values
  MYSQL_ROOT_PASSWORD: Y2hhbmdlbWU=  # changeme
  MYSQL_DATABASE: d29yZHByZXNz       # wordpress
  MYSQL_USER: d29yZHByZXNz           # wordpress
  MYSQL_PASSWORD: d29yZHByZXNzcGFzcw== # wordpresspass